version: "3.8"
# un nouveau commentaire
volumes:
  mariaclub: #déclaration du volume pour la base

services:

  # container de bdd
  clubbase: #nom de service
    container_name: baseclub
    image: mariadb:latest
    ports:
      - '3309:3306'
    volumes:
      - mariaclub:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: UTC
      MYSQL_ROOT_PASSWORD: superadmin
      MYSQL_DATABASE: clubhub
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  # container php
  clubphp:
    container_name: phpclub
    build:
      context: ./Php
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '9001:9000'
    environment:
      DEBUG: '1'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: "100M"
      PHP_UPLOAD_MAX_FILESIZE: "100M"
      TZ: UTC
    volumes:
      - ./App:/var/www/html
    depends_on:
      - clubbase

  # service node
  clubnode:
    tty: true
    container_name: nodeclub
    build:
      context: ./Node
    volumes:
      - ./App:/var/www/html
    restart: always
    environment:
      TZ: UTC
    depends_on:
      - clubphp

  # server web
  clubnginx:
    container_name: nginxclub
    image: nginx:stable-alpine
    #    user: "501:20"
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      TZ: UTC
    volumes:
      - ./App:/var/www/html
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Log:/var/log/nginx/
    depends_on:
      - clubphp
      - clubbase
      - clubnode