vich_uploader:
    db_driver: orm
    mappings:
        player_images:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        team_images:
            uri_prefix: /uploads/images/teams
            upload_destination: '%kernel.project_dir%/public/uploads/images/teams'
            namer: Vich\UploaderBundle\Naming\UniqidNamer